# Generated by Django 5.0 on 2023-12-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=444, null=True)),
                ('owner', models.CharField(max_length=333, null=True)),
                ('type_of', models.CharField(max_length=123, null=True)),
                ('seria', models.CharField(max_length=120, null=True)),
                ('expire', models.CharField(max_length=123, null=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
