# Generated by Django 5.0 on 2023-12-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.CharField(max_length=123, null=True),
        ),
    ]
